name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

conurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact with unique name
        uses: actions/upload-artifact@v4
        with:
          name: site-${{ github.run_id }}
          path: '.'
          retention-days: 1

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-${{ github.run_id }}
          path: ./site

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
